In [1]:
! pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
! pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
! pip install numpy

In [5]:
import numpy as np

## lets do some basic stuff

In [8]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [12]:
a = np.array(5)
a

array(5)

In [13]:
a = np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
print (a.shape)

(3, 5)


In [17]:
print (a.size)

15


In [18]:
print (a.dtype)

int64


In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])